In [1]:
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.

In [4]:
import os
dataset_path = r"../Dataset/PlantVillage-Dataset-master"
print(os.path.exists(dataset_path))

True

In [6]:
classes= os.listdir(dataset_path)
print("number of classes: ", len(classes))

for c in classes[:10]:
    print(c)

number of classes:  16
.gitignore
CITATION.cff
data_distribution_for_SVM
generated_for_paper
generate_data_for_SVM.py
generate_lmdb.sh
generate_mapstring.py
leaf-map.json
leaf_grouping
logs

In [7]:
#exploring the file structure of the dataset
classes = os.listdir(dataset_path)
print(classes)

['.gitignore', 'CITATION.cff', 'data_distribution_for_SVM', 'generated_for_paper', 'generate_data_for_SVM.py', 'generate_lmdb.sh', 'generate_mapstring.py', 'leaf-map.json', 'leaf_grouping', 'logs', 'plant_village.py', 'raw', 'README.md', 'README_HF.md', 'scripts', 'utils']

In [8]:
for item in os.listdir(dataset_path):
    full_path = os.path.join(dataset_path, item)
    if os.path.isdir(full_path):
        print(f"{item} is a directory.")
    else:
        print(f"{item} is a file.")

.gitignore is a file.
CITATION.cff is a file.
data_distribution_for_SVM is a directory.
generated_for_paper is a directory.
generate_data_for_SVM.py is a file.
generate_lmdb.sh is a file.
generate_mapstring.py is a file.
leaf-map.json is a file.
leaf_grouping is a directory.
logs is a directory.
plant_village.py is a file.
raw is a directory.
README.md is a file.
README_HF.md is a file.
scripts is a directory.
utils is a directory.

In [9]:
for i in os.listdir(dataset_path):
    full_path = os.path.join(dataset_path, i)
    if os.path.isdir(full_path):
        print(f"{i} is a directory.")
    else:
        print(f"{i} is a file.")

.gitignore is a file.
CITATION.cff is a file.
data_distribution_for_SVM is a directory.
generated_for_paper is a directory.
generate_data_for_SVM.py is a file.
generate_lmdb.sh is a file.
generate_mapstring.py is a file.
leaf-map.json is a file.
leaf_grouping is a directory.
logs is a directory.
plant_village.py is a file.
raw is a directory.
README.md is a file.
README_HF.md is a file.
scripts is a directory.
utils is a directory.

In [3]:
dataset_path = r"../Dataset/PlantVillage-Dataset-master/raw"
import os
classes = os.listdir(dataset_path)
print("number of classes: ", len(classes))
for c in classes:
    print(c)

number of classes:  3
color
grayscale
segmented

In [5]:
dataset_path = r"../Dataset/PlantVillage-Dataset-master/raw/color"
classes = os.listdir(dataset_path)
print("number of classes: ", len(classes))
for c in classes[:38]:
    print(c)

number of classes:  38
Apple___Apple_scab
Apple___Black_rot
Apple___Cedar_apple_rust
Apple___healthy
Blueberry___healthy
Cherry_(including_sour)___healthy
Cherry_(including_sour)___Powdery_mildew
Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot
Corn_(maize)___Common_rust_
Corn_(maize)___healthy
Corn_(maize)___Northern_Leaf_Blight
Grape___Black_rot
Grape___Esca_(Black_Measles)
Grape___healthy
Grape___Leaf_blight_(Isariopsis_Leaf_Spot)
Orange___Haunglongbing_(Citrus_greening)
Peach___Bacterial_spot
Peach___healthy
Pepper,_bell___Bacterial_spot
Pepper,_bell___healthy
Potato___Early_blight
Potato___healthy
Potato___Late_blight
Raspberry___healthy
Soybean___healthy
Squash___Powdery_mildew
Strawberry___healthy
Strawberry___Leaf_scorch
Tomato___Bacterial_spot
Tomato___Early_blight
Tomato___healthy
Tomato___Late_blight
Tomato___Leaf_Mold
Tomato___Septoria_leaf_spot
Tomato___Spider_mites Two-spotted_spider_mite
Tomato___Target_Spot
Tomato___Tomato_mosaic_virus
Tomato___Tomato_Yellow_Leaf_Curl_Virus

In [6]:
for i in classes :
    class_path = os.path.join(dataset_path, i)

    if os.path.isdir(class_path):

        image_count = len(os.listdir(class_path))
      
        print(f"Class: {i}, Number of images: {image_count}")

Class: Apple___Apple_scab, Number of images: 630
Class: Apple___Black_rot, Number of images: 621
Class: Apple___Cedar_apple_rust, Number of images: 275
Class: Apple___healthy, Number of images: 1645
Class: Blueberry___healthy, Number of images: 1502
Class: Cherry_(including_sour)___healthy, Number of images: 854
Class: Cherry_(including_sour)___Powdery_mildew, Number of images: 1052
Class: Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot, Number of images: 513
Class: Corn_(maize)___Common_rust_, Number of images: 1192
Class: Corn_(maize)___healthy, Number of images: 1162
Class: Corn_(maize)___Northern_Leaf_Blight, Number of images: 985
Class: Grape___Black_rot, Number of images: 1180
Class: Grape___Esca_(Black_Measles), Number of images: 1383
Class: Grape___healthy, Number of images: 423
Class: Grape___Leaf_blight_(Isariopsis_Leaf_Spot), Number of images: 1076
Class: Orange___Haunglongbing_(Citrus_greening), Number of images: 5507
Class: Peach___Bacterial_spot, Number of images: 2297
Class: Peach___healthy, Number of images: 360
Class: Pepper,_bell___Bacterial_spot, Number of images: 997
Class: Pepper,_bell___healthy, Number of images: 1478
Class: Potato___Early_blight, Number of images: 1000
Class: Potato___healthy, Number of images: 152
Class: Potato___Late_blight, Number of images: 1000
Class: Raspberry___healthy, Number of images: 371
Class: Soybean___healthy, Number of images: 5090
Class: Squash___Powdery_mildew, Number of images: 1835
Class: Strawberry___healthy, Number of images: 456
Class: Strawberry___Leaf_scorch, Number of images: 1109
Class: Tomato___Bacterial_spot, Number of images: 2127
Class: Tomato___Early_blight, Number of images: 1000
Class: Tomato___healthy, Number of images: 1591
Class: Tomato___Late_blight, Number of images: 1909
Class: Tomato___Leaf_Mold, Number of images: 952
Class: Tomato___Septoria_leaf_spot, Number of images: 1771
Class: Tomato___Spider_mites Two-spotted_spider_mite, Number of images: 1676
Class: Tomato___Target_Spot, Number of images: 1404
Class: Tomato___Tomato_mosaic_virus, Number of images: 373
Class: Tomato___Tomato_Yellow_Leaf_Curl_Virus, Number of images: 5357

In [8]:
dataset_path = r"D:\FruitDiseaseDissertation\Dataset\PlantDoc-Dataset-master"
directory = os.listdir(dataset_path)
for i in directory:
    full_path = os.path.join(dataset_path, i)
    if os.path.isdir(full_path):
        print(f"{i} is a directory.")
    else:
        print(f"{i} is a file.")

LICENSE.txt is a file.
PlantDoc_Examples.png is a file.
README.md is a file.
test is a directory.
train is a directory.

In [10]:
dataset_path = r"D:\FruitDiseaseDissertation\Dataset\PlantDoc-Dataset-master\train"
directory = os.listdir(dataset_path)
for i in directory:
    full_path = os.path.join(dataset_path,i)

    if os.path.isdir(full_path):

        image_count = len(os.listdir(full_path))

        print(f"Class: {i}, Number of images: {image_count}")

Class: Apple leaf, Number of images: 82
Class: Apple rust leaf, Number of images: 78
Class: Apple Scab Leaf, Number of images: 83
Class: Bell_pepper leaf, Number of images: 53
Class: Bell_pepper leaf spot, Number of images: 62
Class: Blueberry leaf, Number of images: 104
Class: Cherry leaf, Number of images: 47
Class: Corn Gray leaf spot, Number of images: 64
Class: Corn leaf blight, Number of images: 179
Class: Corn rust leaf, Number of images: 106
Class: grape leaf, Number of images: 57
Class: grape leaf black rot, Number of images: 56
Class: Peach leaf, Number of images: 102
Class: Potato leaf early blight, Number of images: 108
Class: Potato leaf late blight, Number of images: 97
Class: Raspberry leaf, Number of images: 112
Class: Soyabean leaf, Number of images: 57
Class: Squash Powdery mildew leaf, Number of images: 124
Class: Strawberry leaf, Number of images: 88
Class: Tomato Early blight leaf, Number of images: 79
Class: Tomato leaf, Number of images: 55
Class: Tomato leaf bacterial spot, Number of images: 101
Class: Tomato leaf late blight, Number of images: 101
Class: Tomato leaf mosaic virus, Number of images: 44
Class: Tomato leaf yellow virus, Number of images: 70
Class: Tomato mold leaf, Number of images: 85
Class: Tomato Septoria leaf spot, Number of images: 140
Class: Tomato two spotted spider mites leaf, Number of images: 2

In [5]:
#standadsing folder name for the comparision
import os
pltvillage_classes = sorted(os.listdir(r"../Dataset/PlantVillage-Dataset-master/raw/color"))
pltdoc_classes = sorted(os.listdir(r"D:\FruitDiseaseDissertation\Dataset\PlantDoc-Dataset-master\train"))
print("PlantVillage classes: ", pltvillage_classes)
print("PlantDoc classes: ", pltdoc_classes)

PlantVillage classes:  ['Apple___Apple_scab', 'Apple___Black_rot', 'Apple___Cedar_apple_rust', 'Apple___healthy', 'Blueberry___healthy', 'Cherry_(including_sour)___Powdery_mildew', 'Cherry_(including_sour)___healthy', 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot', 'Corn_(maize)___Common_rust_', 'Corn_(maize)___Northern_Leaf_Blight', 'Corn_(maize)___healthy', 'Grape___Black_rot', 'Grape___Esca_(Black_Measles)', 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)', 'Grape___healthy', 'Orange___Haunglongbing_(Citrus_greening)', 'Peach___Bacterial_spot', 'Peach___healthy', 'Pepper,_bell___Bacterial_spot', 'Pepper,_bell___healthy', 'Potato___Early_blight', 'Potato___Late_blight', 'Potato___healthy', 'Raspberry___healthy', 'Soybean___healthy', 'Squash___Powdery_mildew', 'Strawberry___Leaf_scorch', 'Strawberry___healthy', 'Tomato___Bacterial_spot', 'Tomato___Early_blight', 'Tomato___Late_blight', 'Tomato___Leaf_Mold', 'Tomato___Septoria_leaf_spot', 'Tomato___Spider_mites Two-spotted_spider_mite', 'Tomato___Target_Spot', 'Tomato___Tomato_Yellow_Leaf_Curl_Virus', 'Tomato___Tomato_mosaic_virus', 'Tomato___healthy']
PlantDoc classes:  ['Apple Scab Leaf', 'Apple leaf', 'Apple rust leaf', 'Bell_pepper leaf', 'Bell_pepper leaf spot', 'Blueberry leaf', 'Cherry leaf', 'Corn Gray leaf spot', 'Corn leaf blight', 'Corn rust leaf', 'Peach leaf', 'Potato leaf early blight', 'Potato leaf late blight', 'Raspberry leaf', 'Soyabean leaf', 'Squash Powdery mildew leaf', 'Strawberry leaf', 'Tomato Early blight leaf', 'Tomato Septoria leaf spot', 'Tomato leaf', 'Tomato leaf bacterial spot', 'Tomato leaf late blight', 'Tomato leaf mosaic virus', 'Tomato leaf yellow virus', 'Tomato mold leaf', 'Tomato two spotted spider mites leaf', 'grape leaf', 'grape leaf black rot']

In [13]:
import pandas as pd
mapping_path =r"D:\FruitDiseaseDissertation\report\paper_mapping.xlsx"
mapping_df = pd.read_excel(mapping_path)
mapping_df.head()

             Plant village         Plant doc Standardized label   Status
0        Apple___Apple_scab  Apple Scab Leaf         apple_scab    MATCH
1         Apple___Black_rot              NaN                TBD  PV_ONLY
2  Apple___Cedar_apple_rust  Apple rust leaf         apple_rust    MATCH
3           Apple___healthy       Apple leaf      apple_healthy    MATCH
4                       NaN              NaN                NaN      NaN

In [5]:
print(mapping_df.columns)

Index(['Plant village ', 'Plant doc', 'Standardized label', 'Status'], dtype='str')

In [14]:
mapping_df['Status'].value_counts()

Status
MATCH        22
PV_ONLY      13
AMBIGUOUS     5
Name: count, dtype: int64

In [15]:
import os
pv_classes = sorted(os.listdir(r"D:\FruitDiseaseDissertation\Dataset\PlantVillage-Dataset-master\raw\color"))

pv_sheet_classes = mapping_df['Plant village '].dropna()

missing_pv = [
    cls for cls in pv_sheet_classes
    if cls not in pv_classes
]

print("plant village name not found :")
print(missing_pv)

plant village name not found :
[]

In [17]:
pd_classes = sorted(os.listdir(r"D:\FruitDiseaseDissertation\Dataset\PlantDoc-Dataset-master\train"))
pd_sheet_classes = mapping_df['Plant doc'].dropna()
missing_pd = []
for cls in pd_sheet_classes:
    if cls not in pd_classes:
        missing_pd.append(cls)
print("plant doc name not found :")
print(missing_pd)

plant doc name not found :
[]

In [19]:
matched_df = mapping_df[mapping_df['Status'] == 'MATCH']
matched_df

,Plant village,Plant doc,Standardized label,Status
0,Apple___Apple_scab,Apple Scab Leaf,apple_scab,MATCH
2,Apple___Cedar_apple_rust,Apple rust leaf,apple_rust,MATCH
3,Apple___healthy,Apple leaf,apple_healthy,MATCH
5,"Pepper,_bell___Bacterial_spot",Bell_pepper leaf spot,bell_pepper_bacterial_spot,MATCH
6,"Pepper,_bell___healthy",Bell_pepper leaf,bell_pepper_healthy,MATCH
11,Corn_(maize)___Cercospora_leaf_spot Gray_leaf_...,Corn Gray leaf spot,corn _gray_leaf_spot,MATCH
12,Corn_(maize)___Common_rust_,Corn rust leaf,corn_common_rust,MATCH
13,Corn_(maize)___Northern_Leaf_Blight,Corn leaf blight,corn_northern_blight,MATCH
16,Grape___Black_rot,grape leaf black rot,grape_black_rot,MATCH
19,Grape___healthy,grape leaf,grape_healthy,MATCH
22,Peach___healthy,Peach leaf,peach_healthy,MATCH
24,Potato___Early_blight,Potato leaf early blight,potato_early_blight,MATCH
25,Potato___Late_blight,Potato leaf late blight,potato_late_blight,MATCH
38,Squash___Powdery_mildew,Squash Powdery mildew leaf,squash_powdery_mildew,MATCH
40,Tomato___Bacterial_spot,Tomato leaf bacterial spot,tomato_leaf_bacterial_spot,MATCH
41,Tomato___Early_blight,Tomato Early blight leaf,tomato_leaf_early_blight,MATCH
42,Tomato___Late_blight,Tomato leaf late blight,tomato_leaf_late_blight,MATCH
43,Tomato___Leaf_Mold,Tomato mold leaf,tomato_leaf_mold,MATCH
44,Tomato___Septoria_leaf_spot,Tomato Septoria leaf spot,tomato_septoria_leaf_spot,MATCH
45,Tomato___Spider_mites Two-spotted_spider_mite,Tomato two spotted spider mites leaf,tomato_leaf_spider_mites two-spotted_mite,MATCH
47,Tomato___Tomato_Yellow_Leaf_Curl_Virus,Tomato leaf yellow virus,tomato_yellow_leaf_curl_virus,MATCH
48,Tomato___Tomato_mosaic_virus,Tomato leaf mosaic virus,tomato_mosaic_virus,MATCH

In [20]:
ambiguous_df = mapping_df[mapping_df["Status"] == "AMBIGUOUS"]
ambiguous_df

,Plant village,Plant doc,Standardized label,Status
9,Cherry_(including_sour)___healthy,Cherry leaf,TBD,AMBIGUOUS
29,NaN,Raspberry leaf,TBD,AMBIGUOUS
31,NaN,Soyabean leaf,TBD,AMBIGUOUS
36,NaN,Strawberry leaf,TDB,AMBIGUOUS
50,NaN,Tomato leaf,TBD,AMBIGUOUS

In [21]:
dataset_specific_df = mapping_df[
    mapping_df["Status"].isin(["PV_ONLY", "PD_ONLY"])
 ]

dataset_specific_df

,Plant village,Plant doc,Standardized label,Status
1,Apple___Black_rot,NaN,TBD,PV_ONLY
8,Cherry_(including_sour)___Powdery_mildew,NaN,cherry_powdery_mildew,PV_ONLY
14,Corn_(maize)___healthy,NaN,corn_healthy,PV_ONLY
17,Grape___Esca_(Black_Measles),NaN,grape_esca_measles,PV_ONLY
18,Grape___Leaf_blight_(Isariopsis_Leaf_Spot),NaN,grape_leaf_blight,PV_ONLY
21,Peach___Bacterial_spot,NaN,peach_bacterial_spot,PV_ONLY
26,Potato___healthy,NaN,potato_healthy,PV_ONLY
28,Raspberry___healthy,NaN,raspberry_healthy,PV_ONLY
30,Soybean___healthy,NaN,soybean_healthy,PV_ONLY
34,Strawberry___Leaf_scorch,NaN,strawberry_leaf_scorch,PV_ONLY
35,Strawberry___healthy,NaN,strawberry_healthy,PV_ONLY
46,Tomato___Target_Spot,NaN,tomato_target_spot,PV_ONLY
49,Tomato___healthy,NaN,tomato_leaf_healthy,PV_ONLY